# apiVersion: v1
# kind: Service
# metadata:
#   name: theera-tenant-fe
#   namespace: theera-qa
# spec:
#   clusterIP: 10.72.10.22
#   clusterIPs:
#   - 10.72.10.22
#   externalTrafficPolicy: Cluster
#   internalTrafficPolicy: Cluster
#   ipFamilies:
#   - IPv4
#   ipFamilyPolicy: SingleStack
#   ports:
#   - nodePort: 30007
#     port: 3000
#     protocol: TCP
#     targetPort: 3000
#   selector:
#     app: host-fe
#   sessionAffinity: None
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: theera-tenant-fe
spec:
  type: NodePort
  selector:
    app: tenant-fe
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3000
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30008