apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tenant-fe
  name: tenant-fe
  namespace: theera-qa
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tenant-fe
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tenant-fe
    spec:
      containers:
      - image: duannd95/tenantfe:1.2 #update
        imagePullPolicy: IfNotPresent
        name: tenant-fe
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30


